[package]
name = "plasm"
version = "0.1.0"
authors = ["Francesco Magliocca <franciman12@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
